imports:
    - { resource: services_seller.yml }
    - { resource: services_product.yml }
    - { resource: services_category.yml }
    - { resource: services_order.yml }

services:

    monolog.formatter.logstash:
        class: Monolog\Formatter\LogstashFormatter
        arguments: ["%symfony2biso_log_stash_key%"]

    monolog.handler.stream:
        class: Monolog\Handler\RotatingFileHandler
        arguments: ["%kernel.root_dir%/logs/", "%symfony2biso_log_redis_key%"]
        calls:
            - [setFormatter, ["@monolog.formatter.logstash"]]

    http_client:
        class: GuzzleHttp\Client


# Symfony2Biso ----------------------------------------------------------------


    app.tokens.action_listener:
        class: AppBundle\Application\Api\v1\Auth\TokenListener
        arguments: ["@market_repository", "@seller_repository"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\User"]

    configuration_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\Configuration"]

    market_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["AppBundle\\Infrastructure\\Core\\Market"]

